name: Deploy to Aliyun
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build --platform linux/amd64 -t rico-server .
      
      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@v1
        with:
          region-id: cn-shenzhen
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_SECRET_KEY }}
      
      - name: Push to ACR
        run: |
          docker tag rico-server registry.cn-shenzhen.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/rico-server:latest
          docker push registry.cn-shenzhen.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/rico-server:latest
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull registry.cn-shenzhen.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/rico-server:latest
            docker stop rico-server || true
            docker rm rico-server || true
            docker run -d --name rico-server -p 3000:3000 --env-file /root/rico-server.env registry.cn-shenzhen.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/rico-server:latest
